version: "3.8"

services:
  server:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Hard-coded non-sensitive values
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:5000
      - SESSION_SECRET=your_session_secret_change_in_production
      - ADMIN_EMAILS=mikser.kowalski@gmail.com

      # Database connection (determined by Docker Compose networking)
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=storage_db

      # Sensitive values passed from host environment
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=storage_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
